services:
  - type: web
    name: car-truck-manager-prototype
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
