#!/usr/bin/env python3
"""Generate seed SQL for SPU + SKU from Excel PRODUCT INFORMATION sheet."""
import openpyxl
import uuid

wb = openpyxl.load_workbook(
    'reference/appSalesReport/Socialbean 2026 - STOCK MANAGEMENT.xlsx',
    data_only=True
)
ws = wb['PRODUCT INFORMATION']

spus = {}
skus = []

def get_brand(wms_code):
    if not wms_code:
        return 'SBT'
    wms = wms_code.strip()
    prefixes = {
        'SAFG': 'SAFG', 'SALC': 'SALC', 'SANN': 'SANN',
        'MBSD': 'MBSD', 'SALM': 'SALM', 'SAAL': 'SAAL', 'GIFT': 'GIFT',
    }
    for prefix, brand in prefixes.items():
        if wms.startswith(prefix):
            return brand
    if wms.startswith('S0'):
        return 'MBSD'
    return 'SBT'

def esc(s):
    if s is None:
        return ''
    return str(s).strip().replace("'", "\\'").replace('\n', ' ').replace('\r', '').replace('\t', ' ')

for row in ws.iter_rows(min_row=5, max_row=ws.max_row, values_only=True):
    wms_code = row[3]
    if wms_code is None:
        continue
    wms_code = str(wms_code).strip()
    if not wms_code or 'WMS' in wms_code:
        continue

    name_kr = row[4]
    name_en = row[5]
    name_vi = row[6]
    color = row[7]
    unit = row[8]

    spu_code = wms_code[:7] if len(wms_code) >= 7 else wms_code
    brand = get_brand(wms_code)

    if spu_code not in spus:
        spus[spu_code] = {
            'spu_id': str(uuid.uuid4()),
            'spu_code': spu_code,
            'brand_code': brand,
            'name_kr': esc(name_kr),
            'name_en': esc(name_en),
            'name_vi': esc(name_vi),
        }

    sku_name_kr = esc(name_kr) if name_kr else spus[spu_code]['name_kr']
    sku_name_en = esc(name_en) if name_en else spus[spu_code]['name_en']
    sku_name_vi = esc(name_vi) if name_vi else spus[spu_code]['name_vi']
    color_val = esc(color) if color else None
    unit_val = esc(unit) if unit else 'EA'

    skus.append({
        'sku_id': str(uuid.uuid4()),
        'spu_id': spus[spu_code]['spu_id'],
        'spu_code': spu_code,
        'wms_code': wms_code,
        'name_kr': sku_name_kr,
        'name_en': sku_name_en,
        'name_vi': sku_name_vi,
        'color': color_val,
        'unit': unit_val,
    })

ENT_ID = 'ent-socialbean-vn-001'

lines = []
lines.append("-- ============================================================")
lines.append("-- Seed Data: Product Master (SPU + SKU)")
lines.append("-- Source: Socialbean 2026 - STOCK MANAGEMENT.xlsx / PRODUCT INFORMATION")
lines.append(f"-- Entity: {ENT_ID}")
lines.append(f"-- Total SPU: {len(spus)}, Total SKU: {len(skus)}")
lines.append("-- Generated by generate-seed.py")
lines.append("-- ============================================================")
lines.append("")
lines.append("SET NAMES utf8mb4;")
lines.append("USE db_app_sales;")
lines.append("")
lines.append("-- ---- SPU Masters ----")

for spu in spus.values():
    lines.append(
        f"INSERT INTO drd_spu_masters "
        f"(spu_id, ent_id, spu_code, spu_brand_code, spu_name_kr, spu_name_en, spu_name_vi, spu_is_active, spu_created_at, spu_updated_at) "
        f"VALUES ('{spu['spu_id']}', '{ENT_ID}', '{spu['spu_code']}', '{spu['brand_code']}', "
        f"'{spu['name_kr']}', '{spu['name_en']}', '{spu['name_vi']}', 1, NOW(), NOW());"
    )

lines.append("")
lines.append("-- ---- SKU Masters ----")

for sku in skus:
    cv = f"'{sku['color']}'" if sku['color'] else 'NULL'
    lines.append(
        f"INSERT INTO drd_sku_masters "
        f"(sku_id, ent_id, spu_id, sku_wms_code, sku_spu_code, sku_name_kr, sku_name_en, sku_name_vi, "
        f"sku_variant_type, sku_variant_value, sku_unit, sku_prime_cost, sku_is_active, sku_created_at, sku_updated_at) "
        f"VALUES ('{sku['sku_id']}', '{ENT_ID}', '{sku['spu_id']}', '{sku['wms_code']}', '{sku['spu_code']}', "
        f"'{sku['name_kr']}', '{sku['name_en']}', '{sku['name_vi']}', "
        f"'COLOR', {cv}, '{sku['unit']}', 0.00, 1, NOW(), NOW());"
    )

lines.append("")

with open('apps/app-sales-report/seed-product-master.sql', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"Generated: {len(spus)} SPUs, {len(skus)} SKUs")
print(f"Brands: {sorted(set(s['brand_code'] for s in spus.values()))}")
print(f"File: apps/app-sales-report/seed-product-master.sql")
