/**
 * Catalog of fields per data source — drives the {token} autocomplete in
 * Formula Config. Sourced from real Shopee/TikTok export headers (2026-05).
 * Column order matches the platform export so autocomplete is predictable.
 */

import { FORMULA_SECTIONS } from './formula-config-data';

export const DATA_SOURCE_FIELDS: Record<string, string[]> = {
  'Shopee Sales CSV': [
    'Mã đơn hàng',
    'Mã Kiện Hàng',
    'Ngày đặt hàng',
    'Trạng Thái Đơn Hàng',
    'Sản Phẩm Bán Chạy',
    'Lý do hủy',
    'Nhận xét từ Người mua',
    'Mã vận đơn',
    'Đơn Vị Vận Chuyển',
    'Phương thức giao hàng',
    'Loại đơn hàng',
    'Ngày giao hàng dự kiến',
    'Ngày gửi hàng',
    'Thời gian giao hàng',
    'Trạng thái Trả hàng/Hoàn tiền',
    'SKU sản phẩm',
    'Tên sản phẩm',
    'Cân nặng sản phẩm',
    'Tổng cân nặng',
    'SKU phân loại hàng',
    'Tên phân loại hàng',
    'Giá gốc',
    'Người bán trợ giá',
    'Được Shopee trợ giá',
    'Tổng số tiền được người bán trợ giá',
    'Giá ưu đãi',
    'Số lượng',
    'Số lượng sản phẩm được hoàn trả',
    'Tổng số tiền Người mua thanh toán',
    'Tổng giá trị đơn hàng (VND)',
    'Mã giảm giá của Shop',
    'Hoàn Xu',
    'Mã giảm giá của Shopee',
    'Chỉ tiêu Combo Khuyến Mãi',
    'Giảm giá từ combo Shopee',
    'Giảm giá từ Combo của Shop',
    'Shopee Xu được hoàn',
    'Số tiền được giảm khi thanh toán bằng thẻ Ghi nợ',
    'Trade-in Discount',
    'Trade-in Bonus',
    'Phí vận chuyển (dự kiến)',
    'Trade-in Bonus by Seller',
    'Phí vận chuyển mà người mua trả',
    'Phí vận chuyển tài trợ bởi Shopee (dự kiến)',
    'Phí vận chuyển trả hàng (đơn Trả hàng/hoàn tiền)',
    'Tổng số tiền người mua thanh toán',
    'Thời gian hoàn thành đơn hàng',
    'Thời gian đơn hàng được thanh toán',
    'Phương thức thanh toán',
    'Phí cố định',
    'Phí Dịch Vụ',
    'Phí thanh toán',
    'Tiền ký quỹ',
    'Người Mua',
    'Tên Người nhận',
    'Số điện thoại',
    'Tỉnh/Thành phố',
    'TP / Quận / Huyện',
    'Quận',
    'Địa chỉ nhận hàng',
    'Quốc gia',
    'Ghi chú',
    'Yêu cầu hóa đơn',
    'Loại hóa đơn',
    'Họ & Tên',
    'Mã số thuế',
    'Địa chỉ',
    'Email',
  ],
  'Shopee Traffic CSV': [
    'Mã sản phẩm',
    'Sản phẩm',
    'Tình trạng sản phẩm hiện tại',
    'Mã phân loại hàng',
    'Tên Phân Loại',
    'Trạng thái phân loại sản phẩm hiện tại',
    'SKU phân loại',
    'SKU sản phẩm',
    'Doanh số (Đơn đã đặt) (VND)',
    'Doanh số (Đơn đã xác nhận) (VND)',
    'Lượt xem sản phẩm',
    'Lượt nhấp vào sản phẩm',
    'CTR',
    'Tỷ lệ chuyển đổi đơn (Đơn đã đặt)',
    'Tỷ lệ chuyển đổi đơn (Đơn đã xác nhận)',
    'Đơn hàng đã đặt',
    'Đơn đã xác nhận',
    'Sản phẩm (Đơn đã đặt)',
    'Sản phẩm (Đơn đã xác nhận)',
    'Người mua đã đặt hàng',
    'Người mua có đơn đã xác nhận',
    'Tỷ lệ chuyển đổi (Đơn đã đặt)',
    'Tỷ lệ chuyển đổi (Đơn đã xác nhận)',
    'Doanh thu trên mỗi đơn (Đơn đã đặt) (VND)',
    'Doanh thu trên mỗi đơn (Đơn đã xác nhận) (VND)',
    'Lượt hiển thị sản phẩm duy nhất',
    'Lượt nhấp sản phẩm duy nhất',
    'Lượt truy cập sản phẩm',
    'Lượt xem trang sản phẩm',
    'Số lượng khách thoát trang sản phẩm',
    'Tỷ lệ thoát Trang sản phẩm',
    'Lượt click từ Trang tìm kiếm',
    'Lượt thích',
    'Lượt truy cập sản phẩm (Thêm vào giỏ hàng)',
    'Sản phẩm (Thêm vào giỏ hàng)',
    'Tỷ lệ chuyển đổi (theo lượt thêm vào giỏ hàng)',
    'Tỷ lệ mua lại (Đơn đã đặt)',
    'Tỷ lệ đặt hàng lặp lại (Đơn hàng đã được xác nhận)',
    'Số ngày trung bình mà Người mua quay lại đặt hàng (Đơn đã đặt)',
    'Số ngày trung bình để lặp lại đơn hàng (Đơn hàng đã được xác nhận)',
  ],
  'Shopee Ads CSV': [
    'Thứ tự',
    'Tên Dịch vụ Hiển thị',
    'Trạng thái',
    'Loại Dịch vụ Hiển thị',
    'Mã sản phẩm',
    'Nội dung Dịch vụ Hiển thị',
    'Phương thức đấu thầu',
    'Vị trí',
    'Ngày bắt đầu',
    'Ngày kết thúc',
    'Số lượt xem',
    'Số lượt click',
    'Tỷ Lệ Click',
    'Lượt chuyển đổi',
    'Lượt chuyển đổi trực tiếp',
    'Tỷ lệ chuyển đổi',
    'Tỷ lệ chuyển đổi trực tiếp',
    'Chi phí cho mỗi lượt chuyển đổi',
    'Chi phí cho mỗi lượt chuyển đổi trực tiếp',
    'Sản phẩm đã bán',
    'Sản phẩm đã bán trực tiếp',
    'Doanh số',
    'Doanh số trực tiếp',
    'Chi phí',
    'ROAS',
    'ROAS trực tiếp',
    'ACOS',
    'ACOS trực tiếp',
    'Lượt xem Sản phẩm',
    'Lượt clicks Sản phẩm',
    'Tỷ lệ Click Sản phẩm',
    'Voucher Amount',
    'Vouchered Sales',
  ],
  'Shopee Brand Ads CSV': [
    'Sequence',
    'Campaign Name',
    'Campaign ID',
    'Status',
    'Start Date',
    'End Date',
    'Budget',
    'Impression',
    'Clicks',
    'CTR',
    'Reach',
    'Page Views',
    'Unique Visitors',
    'CPM',
    'Expense',
  ],
  'Shopee Off-Platform Ads CSV': [
    'Shop ID',
    'Tên Shop',
    'Khoảng thời gian',
    'Ngày',
    'Lượt hiển thị',
    'Lượt click',
    'Tỷ lệ click',
    'Đơn hàng',
    'GMV(VND)',
    'GMV(USD)',
    'Chi phí(VND)',
    'Chi phí(USD)',
    'ROI',
    'Chi phí cho mỗi đơn hàng(VND)',
    'Chi phí cho mỗi đơn hàng(USD)',
    'Giá trị đơn hàng trung bình(VND)',
    'Giá trị đơn hàng trung bình(USD)',
  ],
  'Shopee Affiliate CSV': [
    'Mã đơn hàng',
    'Trạng thái đơn hàng',
    'Trạng thái gian lận',
    'Thời gian đặt hàng',
    'Thời gian đơn hàng hoàn thành',
    'Thời gian chuyển đổi hoàn tất',
    'Mã sản phẩm',
    'Tên sản phẩm',
    'Model id',
    'L1 Ngành hàng toàn cầu',
    'L2 Ngành hàng toàn cầu',
    'L3 Ngành hàng toàn cầu',
    'Mã khuyến mãi',
    'Giá(₫)',
    'Số lượng',
    'Tên đối tác',
    'Tài khoản Tiếp thị liên kết',
    'MCN được liên kết',
    'Mã hoa hồng',
    'Đối tác chiến dịch',
    'Loại chiến dịch',
    'Giá trị đặt hàng(₫)',
    'Số tiền hoàn(₫)',
    'Loại đơn hàng',
    'Hoa hồng Xtra trên sản phẩm(₫)',
    'Hoa hồng Xtra trên sản phẩm mà đơn vị tiếp thị liên kết nhận được(₫)',
    'Tỷ lệ hoa hồng Xtra trên sản phẩm mà đơn vị tiếp thị liên kết nhận được',
    'Hoa hồng Xtra trên sản phẩm mà MCN nhận được(₫)',
    'Tỷ lệ hoa hồng Xtra trên sản phẩm mà MCN nhận được',
    'Hoa hồng Xtra trên đơn hàng(₫)',
    'Hoa hồng Xtra trên đơn hàng mà đơn vị tiếp thị liên kết nhận được(₫)',
    'Hoa hồng Xtra trên đơn hàng mà MCN nhận được(₫)',
    'Ghi chú sản phẩm',
    'Kênh',
    'Chi phí(₫)',
    'Trạng thái khấu trừ',
    'Phương pháp khấu trừ',
    'Thời gian khấu trừ',
  ],
  'TikTok Sales CSV': [
    'Order ID',
    'Order Status',
    'Order Substatus',
    'Cancelation/Return Type',
    'Normal or Pre-order',
    'SKU ID',
    'Seller SKU',
    'Product Name',
    'Variation',
    'Quantity',
    'Sku Quantity of return',
    'SKU Unit Original Price',
    'SKU Subtotal Before Discount',
    'SKU Platform Discount',
    'SKU Seller Discount',
    'SKU Subtotal After Discount',
    'Shipping Fee After Discount',
    'Original Shipping Fee',
    'Shipping Fee Seller Discount',
    'Shipping Fee Platform Discount',
    'Payment platform discount',
    'Taxes',
    'Order Amount',
    'Order Refund Amount',
    'Created Time',
    'Paid Time',
    'RTS Time',
    'Shipped Time',
    'Delivered Time',
    'Cancelled Time',
    'Cancel By',
    'Cancel Reason',
    'Fulfillment Type',
    'Warehouse Name',
    'Tracking ID',
    'Delivery Option',
    'Shipping Provider Name',
    'Buyer Message',
    'Buyer Username',
    'Recipient',
    'Phone #',
    'Country',
    'Province',
    'District',
    'Commune',
    'Detail Address',
    'Additional address information',
    'Payment Method',
    'Weight(kg)',
    'Product Category',
    'Package ID',
    'Seller Note',
    'Checked Status',
    'Checked Marked by',
  ],
  'TikTok Traffic CSV': [
    'ID',
    'Sản phẩm',
    'Trạng thái',
    'GMV',
    'Số món bán ra',
    'Đơn hàng',
    'GMV tab Cửa hàng',
    'Số món bán ra qua Tab Cửa hàng',
    'Lượt hiển thị bài niêm yết trong tab Cửa hàng',
    'Lượt xem trang từ tab Cửa hàng',
    'Lượt xem trang độc nhất từ tab Cửa hàng',
    'Khách hàng mua sản phẩm độc nhất tại tab Cửa hàng',
    'Tỷ lệ nhấp vào Shop Tab',
    'Tỷ lệ chuyển đổi Shop Tab',
    'GMV LIVE',
    'Số món bán ra trong LIVE',
    'Lượt hiển thị LIVE',
    'Lượt xem trang từ LIVE',
    'Lượt xem trang duy nhất từ LIVE',
    'Khách hàng sản phẩm duy nhất của LIVE',
    'Tỷ lệ nhấp vào LIVE',
    'Tỷ lệ chuyển đổi của LIVE',
    'GMV video',
    'Số món bán ra từ video',
    'Lượt hiển thị của video',
    'Lượt xem trang từ video',
    'Lượt xem trang duy nhất từ video',
    'Khách hàng sản phẩm duy nhất của video',
    'Tỷ lệ nhấp vào video',
    'Tỷ lệ chuyển đổi của video',
    'GMV thẻ sản phẩm',
    'Số món bán ra từ thẻ sản phẩm',
    'Lượt hiển thị thẻ sản phẩm',
    'Lượt xem trang từ thẻ sản phẩm',
    'Lượt xem trang duy nhất từ thẻ sản phẩm',
    'Khách hàng duy nhất của thẻ sản phẩm',
    'Tỷ lệ nhấp vào thẻ sản phẩm',
    'Tỷ lệ chuyển đổi của thẻ sản phẩm',
  ],
  'TikTok Affiliate CSV': [
    'Tên người dùng của nhà sáng tạo',
    'GMV liên kết',
    'GMV LIVE của liên kết',
    'GMV video link bán hàng của liên kết',
    'GMV thẻ sản phẩm của liên kết',
    'Sản phẩm liên kết đã bán',
    'Số món bán ra',
    'Hoa hồng ước tính',
    'Phí cố định ước tính',
    'Giá trị đơn hàng trung bình',
    'Trang trưng bày sản phẩm liên kết',
    'Đơn hàng liên kết',
    'Tỷ lệ nhấp (CTR)',
    'Lượt hiển thị sản phẩm',
    'Khách hàng liên kết trung bình',
    'Buổi LIVE liên kết',
    'Video link bán hàng của liên kết',
    'GMV cộng tác mục tiêu',
    'Hoa hồng ước tính trong cộng tác mục tiêu',
    'GMV cộng tác mở',
    'Hoa hồng ước tính của cộng tác mở',
    'GMV đã hoàn tiền từ liên kết',
    'Mặt hàng từ liên kết đã hoàn tiền',
    'Người theo dõi của liên kết',
  ],
  'Prime Cost Table': [
    'SKU',
    'Variation ID',
    'Prime Cost',
    'Selling Price',
    'Listing Price',
  ],
  'Manual Input': [
    'Total Affiliate Booking Fee',
    'Total Livestream Fee — Shopee',
    'Total Livestream Fee — TikTok',
    'Total Ad Spending — TikTok',
    'Transaction Fee',
    'TikTok Shop Commission',
    'Seller Shipping Fee',
    'Exclusive Benefit Access Fee',
    'Voucher Xtra Service Fee',
    'Order Processing Fee',
    'SFR Service Fee',
    'FX Rate (VND per KRW)',
  ],
};

// "Calculated" → all metric names already computed in Formula Config
let _calculatedFieldsCache: string[] | null = null;
export function getCalculatedFields(): string[] {
  if (_calculatedFieldsCache) return _calculatedFieldsCache;
  _calculatedFieldsCache = FORMULA_SECTIONS.flatMap((s) => s.items.map((it) => it.metric));
  return _calculatedFieldsCache;
}

/**
 * Returns fields available given the selected data sources, grouped by source.
 * "Calculated" auto-expands to all 93 metrics from FORMULA_SECTIONS.
 */
export function getAvailableFields(
  selectedSources: string[],
): { source: string; fields: string[] }[] {
  return selectedSources
    .map((src) => {
      if (src === 'Calculated') return { source: 'Calculated', fields: getCalculatedFields() };
      const fields = DATA_SOURCE_FIELDS[src];
      if (!fields) return null;
      return { source: src, fields };
    })
    .filter((g): g is { source: string; fields: string[] } => g !== null);
}

/** Flat set for token validation. */
export function buildFieldSet(selectedSources: string[]): Set<string> {
  const set = new Set<string>();
  for (const g of getAvailableFields(selectedSources)) {
    for (const f of g.fields) set.add(f);
  }
  return set;
}
