// Report labels — independent of next-intl (export endpoints accept ?lang=)

import type { CostType, Language } from '@repo/api-types';

const LABELS = {
  en: {
    title: {
      costs: 'Cost report',
      trips: 'Trip report',
      accidents: 'Accident report',
      repairs: 'Repair / Maintenance report',
    },
    period: 'Period',
    generatedAt: 'Generated',
    columns: {
      date: 'Date',
      time: 'Time',
      endTime: 'End',
      type: 'Type',
      vehicle: 'Vehicle',
      vehicleType: 'Model',
      amount: 'Amount',
      currency: 'Currency',
      description: 'Description',
      status: 'Status',
      submitter: 'Submitted by',
      approver: 'Approved by',
      passenger: 'Passenger',
      driver: 'Driver',
      pickup: 'Pickup',
      destination: 'Destination',
      note: 'Note',
      attachments: 'Files',
      total: 'Total',
    },
    costType: {
      FUEL: 'Fuel',
      OIL_CHANGE: 'Oil change',
      ACCIDENT: 'Accident',
      MEAL: 'Meal',
      REPAIR_MAINTENANCE: 'Repair / Maintenance',
    } satisfies Record<CostType, string>,
  },
  ko: {
    title: {
      costs: '비용 보고서',
      trips: '운행 보고서',
      accidents: '사고 보고서',
      repairs: '수리·정비 보고서',
    },
    period: '기간',
    generatedAt: '생성 시각',
    columns: {
      date: '일자',
      time: '시각',
      endTime: '종료',
      type: '유형',
      vehicle: '차량',
      vehicleType: '모델',
      amount: '금액',
      currency: '통화',
      description: '내용',
      status: '상태',
      submitter: '제출자',
      approver: '승인자',
      passenger: '탑승자',
      driver: '기사',
      pickup: '출발지',
      destination: '도착지',
      note: '비고',
      attachments: '파일',
      total: '합계',
    },
    costType: {
      FUEL: '주유',
      OIL_CHANGE: '엔진오일',
      ACCIDENT: '사고',
      MEAL: '식비',
      REPAIR_MAINTENANCE: '수리·정비',
    } satisfies Record<CostType, string>,
  },
  vi: {
    title: {
      costs: 'Báo cáo chi phí',
      trips: 'Báo cáo chuyến đi',
      accidents: 'Báo cáo tai nạn',
      repairs: 'Báo cáo sửa chữa / bảo dưỡng',
    },
    period: 'Kỳ báo cáo',
    generatedAt: 'Tạo lúc',
    columns: {
      date: 'Ngày',
      time: 'Giờ',
      endTime: 'Kết thúc',
      type: 'Loại',
      vehicle: 'Xe',
      vehicleType: 'Loại xe',
      amount: 'Số tiền',
      currency: 'Đơn vị',
      description: 'Mô tả',
      status: 'Trạng thái',
      submitter: 'Người gửi',
      approver: 'Người duyệt',
      passenger: 'Người đi',
      driver: 'Tài xế',
      pickup: 'Điểm đón',
      destination: 'Điểm đến',
      note: 'Ghi chú',
      attachments: 'File',
      total: 'Tổng',
    },
    costType: {
      FUEL: 'Đổ xăng',
      OIL_CHANGE: 'Thay dầu',
      ACCIDENT: 'Tai nạn',
      MEAL: 'Ăn uống',
      REPAIR_MAINTENANCE: 'Sửa chữa / Bảo dưỡng',
    } satisfies Record<CostType, string>,
  },
} as const;

export function labelsFor(lang: Language) {
  return LABELS[lang];
}
